### ISSUE TITLE
Color Banding

### ISSUE THREAD

**Issue by seannowotny** [FairplexVR/AgX-Luts-Unity#2]
Hi! Thanks a lot for making these LUTs available. They have a lot of potential!

To some degree it has an amazing effect but it also causes color banding.

Here are my settings (HDRP):
![Unity_D5m0RqQeQT](https://github.com/FairplexVR/AgX-Tonemapping-Unity/assets/21989324/1ae6ce45-ced1-435f-ad65-daa6b80a2d26)

![Unity_nxkXddnCWa](https://github.com/FairplexVR/AgX-Tonemapping-Unity/assets/21989324/791bc819-4bd1-4a8b-9366-836361cd5d55)

Custom post-processing:
![Unity_sTwtZUAnIP](https://github.com/FairplexVR/AgX-Tonemapping-Unity/assets/21989324/5e82f271-4a50-490c-b6ca-d38d16b4ef11)

Adjusted custom post processing + AgX - High Contrast (the snow is now looking weird)
![Unity_Yn6f9zsRCw](https://github.com/FairplexVR/AgX-Tonemapping-Unity/assets/21989324/af437499-e7c4-4b77-8bb8-bc78f1c70949)

AgX - High Contrast only (very obvious color banding)
![Unity_EgifY2Wtjs](https://github.com/FairplexVR/AgX-Tonemapping-Unity/assets/21989324/954c342d-6ea3-4fc5-afa5-51ecf5614a46)

**Comment by meenphie** [comment]
Those are compression banding, make sure that the texture compression is set to 'None' for Unity custom LUTs.
