### ISSUE TITLE
Unity 2018 issue

### ISSUE THREAD

**Issue by Hanmen-lab** [FairplexVR/AgX-Luts-Unity#4]
![image](https://github.com/FairplexVR/AgX-Tonemapping-Unity/assets/45272500/3667a552-11c1-4746-9546-8090a6f13f99)

Hello, I got this in Unity 2018 BIRP. What I'm doing wrong?
I've tried both 2D and Cube texture type.
![image](https://github.com/FairplexVR/AgX-Tonemapping-Unity/assets/45272500/71d3b834-e715-4230-9f59-c203d78594f4)

Just got blank screen 
![image](https://github.com/FairplexVR/AgX-Tonemapping-Unity/assets/45272500/5bd63ded-69f2-4ff0-b5ff-4f08267caa69)

**Comment by Hanmen-lab** [comment]
Can you convert to asset format Like other CUBE LUTs in HDRP provided?

**Comment by Hanmen-lab** [comment]
https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@12.0/manual/LUT-Authoring-Photoshop.html

**Comment by meenphie** [comment]
I have added a package for Unity 2018. Let me know if you can import that one in your project:

https://github.com/FairplexVR/AgX-Tonemapping-Unity/releases/tag/1.0.0

**Comment by Hanmen-lab** [comment]
Thank you! It's working now
